# Generated by Django 4.2.7 on 2025-11-01 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('user visit', 'user visit'), ('fast visit', 'fast visit')], max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField()),
                ('required_game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visits.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('played_game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visits.game')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visits.visit')),
            ],
        ),
    ]
