# Generated by Django 4.2.7 on 2025-11-23 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_name', models.CharField(default='Basky Device', max_length=100)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ws_host', models.CharField(blank=True, max_length=100)),
                ('ws_port', models.IntegerField(default=8080)),
                ('ssid', models.CharField(blank=True, max_length=100)),
                ('signal_strength', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connected', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configurations',
                'ordering': ['-last_connected'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('mode', models.CharField(default='normal', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Device Statuses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('total_readings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapy Session',
                'verbose_name_plural': 'Therapy Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('shoulder_pitch', models.FloatField(default=0)),
                ('shoulder_roll', models.FloatField(default=0)),
                ('shoulder_yaw', models.FloatField(default=0)),
                ('elbow_pitch', models.FloatField(default=0)),
                ('elbow_roll', models.FloatField(default=0)),
                ('elbow_yaw', models.FloatField(default=0)),
                ('wrist_pitch', models.FloatField(default=0)),
                ('wrist_roll', models.FloatField(default=0)),
                ('wrist_yaw', models.FloatField(default=0)),
                ('hand_pitch', models.FloatField(default=0)),
                ('hand_roll', models.FloatField(default=0)),
                ('hand_yaw', models.FloatField(default=0)),
                ('force_value', models.FloatField(default=0)),
                ('exercise_type', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('session_duration', models.IntegerField(default=0)),
                ('mode', models.CharField(default='normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_id', '-timestamp'], name='devices_sen_device__6e3463_idx'), models.Index(fields=['exercise_type', '-timestamp'], name='devices_sen_exercis_fec13c_idx')],
            },
        ),
    ]
